server:
  port: 8051

spring:
  application:
    name: config_service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zuguangz97/springlive-config
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8050/eureka}


